services:
  apache:
    image: httpd:latest
    container_name: mypiggy_apache
    volumes:
      - ./apache/mypiggy.conf:/usr/local/apache2/conf/httpd.conf
      - ./frontend/public:/home/tmribeiro/eclipse-workspace/mypiggy/frontend/public
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    container_name: mypiggy_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mypiggy_postgres:5432/mydb
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mypiggy_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://mypiggy_backend:8080/api/

  postgres:
    image: postgres:latest
    container_name: mypiggy_postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mypiggy_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
